import React from 'react';


class PrivacyPage extends React.Component {
    render() {
        return (
            <div className="container">
            <h3>Privacy Policy</h3>
            <p>Please read our Privacy Policy to understand our practices which governs your use of the Application. Any information (including your personal information and/or sensitive personal data or information) provided by you on the Application will be collected, stored, processed, transferred or shared by us in accordance with our Privacy Policy. These Terms are deemed to incorporate the Privacy Policy posted on this Site and accessible/embedded in the Application.</p>
            <h4> Information Collection </h4>
            <p>"Personally Identifiable Information" means any information that either on its own or when combined with certain other information can identify an individual and for the purpose of this Privacy Policy.</p>
            <p>Medicine Reminder (www.medihelp4u.com) will obtain the following types of information from or concerning to you or your / computer / mobile device, which may include personal information that can be used to identify you as specified below:</p>
            <p>User Provided Information: You provide certain Personally Identifiable Information, including but not limited to Your mobile phone number, name, gender and date of birth, physical address, property address, IP Address and mobile device information to Medicine Reminder when choosing to participate in the use of the Website / Application and the Services, such as registering as a user, messaging other Medicine Reminder users, uploading images or journals. By permitting us to collect Personally Identifiable Information, you hereby agree to provide Medicine Reminder a right to use such information for providing Services and also warrant that you have all requisite rights in your favor to share this information with Medicine Reminder. To ensure a better user experience, Medicine Reminder may, access including but not limited to your gallery, camera, microphone and your current location to ensure correct functioning of features like uploading images, videos and shootouts and any other electronic facility that will be made available in future.</p>
            <p>Medicine Reminder may receive data whenever you connect with website or an application through Medicine Reminder (such as during status update, when you connect to other sites/applications and in which case Medicine Reminder posts to these sites/applications on Your behalf ). This may include date and time you use the application, the web address, IP address information, browser and if you are logged into Medicine Reminder and your authentication tokens used on such sites. Your authentication tokens may be saved on the server for the sole purpose of seamless posting to the same site by you in the future through the Application.</p>
            <h4> Storage of information  </h4>
            <p>We store your personal data and information in our database. We reserve a right to retain your personal data and information for indefinite period even after the termination of your account. This is done for security reasons and other future purposes.</p>
            <h4> Security of Personal Information  </h4>
            <p>We have implemented commercially reasonable physical, managerial, operational and technical security measures to protect the loss, misuse and alteration and to preserve the security of the Personally Identifiable Information in our care. Our security practices and procedures limit access to personal information on need to know basis only.</p>
            <p>Such measures may include, where appropriate, the use of firewalls, secure server facilities, implementing proper access rights management systems and processes, careful selection of processors, standard authentication and encryption policies for our servers and other technically, physically and commercially reasonable measures. </p>
            <p>However, Medicine Reminder cannot guarantee in any way with respect to any Personally Identifiable Information or Contents that you upload transmit, share or display through the website/Application, the Services and you do so at your own risk.</p>
            <p>Using unsecured or other unprotected networks to send messages and use of other features through the Medicine Reminder application is not recommended. If Medicine Reminder learns of a security breach, then we may attempt to notify you electronically so that you can take appropriate protective steps.</p>
            <h4> Cookies  </h4>
            <p>We shall use "Cookies" which are small pieces of information that are stored by your browser on your computer's hard drive. The use of cookies is very common on the Internet. Cookies are useful for enabling the browser to remember information specific to a given user. We place both permanent and temporary cookies in your computer's hard drive. The cookies do not contain any of your personally identifiable information. Cookies allow us to serve you better and more efficiently, and to personalize your experience at our Website. These types of cookies allow you to log in without having to type your log - in name each time (only your password is needed). We may also use such cookies to display an advertisement to you while you are on the Website.</p>
            <p>Medicine Reminder may use cookies and other technologies such as web beacons, web storage, unique advertising identifiers to collect information about your use of our Services and your device. We may use similar technologies to collect information when you interact with services offered by any third party through the Application. We might collect passively tracked activity data including but not limited to accelerometer samples, step counter and pedometer data.</p>
            <p>We may collect location data for use in the improvement of Services and users may also voluntarily share their location with other users via the Application.</p>
            <p>Service Usage and Transactional Information: For enabling you to make payments using our Services, we may, upon your consent, store your financial information such as your bank account or details mentioned on your credit cards or debit cards, or other payment instrument details etc. that are required for a successful transaction. Further, for certain Services, including our bill payment service, we require your bill payment account information such as your account number, payment history, your account history with us etc. We also store transaction details such as amount spent, merchant name, transaction ID, date and time of transaction, of your e-commerce transactions.</p>
            <p>Further, we may also store information relating to your income and lifestyle levels. If the recipient can be messaged via the Application, the message is delivered to that recipient via data service routed through our servers. Any messages that are undelivered are held on the Medicine Reminder servers until they can be delivered or for a period of 30 days whichever is earlier. Messages and files that are sent through the Service temporarily reside on our servers for a short period of time until delivery of such messages or files to the intended recipient is complete. We may use third party servers having industry standard security measures to provide you the Services.</p>
            <p>Medicine Reminder may retain date and time stamp information associated with successfully delivered messages, the Medicine Reminder members involved in the messages and any other meta-data associated with your use of our Services as well as any other information which Medicine Reminder is legally compelled to collect in accordance with retention policies applicable under Indian law.</p>
            <h4> 	Use of Information  </h4>
            <p>We do not sell Your Personally Identifiable Information that we collect with any third parties for use for commercial, advertising and or similar marketing purposes without your consent.</p>
            <h4> Passwords and account security </h4>
            <p>You agree and understand that you are responsible to MEDICINE REMINDER and to third parties for maintaining the confidentiality of passwords associated with any account you use to access the Service. You will be solely responsible for all activities that occur under your account. MEDICINE REMINDER will take due care to ensure the confidentiality of your credentials. You agree and acknowledge that in the very unlikely event of your credentials becoming known to a third party on account of an intrusion into MEDICINE REMINDER'S data base, MEDICINE REMINDER shall not be made liable for the resulting damages. If you become aware of any unauthorized use of your password or of your account, you agree to notify the concerned official at MEDICINE REMINDER immediately.</p>
            <h4> Choice/Opt-Out </h4>
            <p>We provide all users with the opportunity to opt-out of receiving non-essential (promotional, marketing-related) communications from us on behalf of our partners, and from us in general, after setting up an account.</p>
            <h4> Security Precautions </h4>
            <p>Our Website/ mobile application has stringent security measures in place to protect the loss, misuse, and alteration of the information under our control. Whenever you change or access your account information, we offer the use of a secure server. Once your information is in our possession we adhere to strict security guidelines, protecting it against unauthorized access.</p>
            <h4> Your Conduct </h4>
            <p>(a) You shall be solely responsible for all contents that you use our website / application, upload, transmit, share or display through the Application or the Site, (collectively the “Contents”) including but not limited to any photos, profiles (including Your name and image), messages, information, text, video, music, third party links and automatic submission of your session logs. Medicine Reminder does not guarantee as to the validity, accuracy or legal status or confidentiality with respect to any Contents and You shall be solely responsible and assume all risks for any consequences of uploading, posting, transfer or disclosure of the Contents. You hereby confirm and warrant that the Contents do not violate the representation and warranties provided in terms & conditions. You further agree that Content you transmit over the Application will not contain third party copyrighted material, or material that is subject to other third party proprietary rights, unless you have permission from the rightful owner of the material or you are otherwise legally entitled to use or transmit the material and to grant Medicine Reminder all of the license rights granted herein.</p>
            <p>(b) You represent and warrant that: (i) your use of the Application or the Services will be solely for purposes that are permitted by these Terms; (iii) you will provide true and accurate information (including your mobile phone number and other numbers in your address book) for use of the Application or the Services; (iv) your use of the Application or the Services will at all times comply with applicable laws.</p>
            <h4> Sharing Personally Identifiable Information </h4>
            <p>We may share Your Personally Identifiable Information and Contents:</p>
            <p>1. To provide Services to you and to allow you to transmit your user-generated content to other users;</p>
            <p>2. To provide you with relevant content, Services or advertisements in accordance with your usage of the Application and any other information available with us. </p>
            <p>3. To verify your identity.</p>
            <p>4. To monitor, detect and deter unauthorized or fraudulent use of, or abuse of, Services to improve and/or optimize the Services;</p>
            <p>5. To enable us to provide customer support, and to respond effectively to your inquiries and claims;</p>
            <p>6. To conduct user surveys;</p>
            <p>7. To provide you with information regarding the Services;</p>
            <p>8. To measure the effectiveness of advertisements that we place on the Internet or in other media;</p>
            <p>9. To notify you of any other important information regarding Services, if necessary;</p>
            <p>10. To aggregate anonymized statistical data regarding Services; and</p>
            <p>11. To comply with applicable laws or legal obligations.</p>
            <p>12. We may disclose your information for law enforcement if needed.</p>
            <h4> Others </h4>
            <p>If we provide you with more specific purposes of use either at the time we ask you to provide your personal information or through other means, then such notice will take precedence.</p>
            <p>We collect and store your service usage and transactional information in order to enable you to view certain details of all your transactions usage which have been made using our Services, to provide you uninterrupted and satisfactory Services, to administer our relationship with you, to comply with any statutory or regulatory requirement, to monitor your use of our Services for the purposes of ensuring compliance with our user rules.</p>
            <p>You agree that Medicine Reminder has the right to monitor the Application electronically from time to time and to disclose information as may be necessary to satisfy any law, regulation or other governmental request, to operate the Application properly for justified purposes that are relevant for the features and functionalities of the Application and Services opted by you, or to protect itself or its subscribers. We may transfer your Personally Identifiable Information or other information collected, stored, processed by Medicine Reminder to any other entity or organization located in India or outside India only in case it is necessary for providing services to you in connection with Services / Application. Except with your consent including under this Agreement for specified purposes, We will not disclose any Personally Identifiable Information to any third party expect for the purpose of providing you Services. We will cooperate with the appropriate law enforcement authorities in investigating claims of illegal activity.</p>
            <p>You may choose not to submit Personally Identifiable Information through Medicine Reminder application in which case we may not be able to provide you part or full services in connection with the Application. If you do not agree with any of the Terms including our Privacy Policy, You may delete your account or not access download and use the website/Application and/or the Services. Upon deletion of your account, Your Personally Identifiable Information and any associated Contents, except to the extent required to be retained under applicable law, will be deleted from our servers.</p>
            <p>In the interest of protecting your privacy and for security measures, Medicine Reminder ensures to take reasonable steps to identify and authorize you before registering your mobile phone number and granting you use of the Medicine Reminder application. Upon use of the Application or the Services, you authorize us to contact you regarding any promotions / notifications pertaining to Medicine Reminder Application, notwithstanding that your number may be registered in the respective do not call Registry in your jurisdiction.</p>
            <h4> Grievance Officer </h4>
            <p>In accordance with Information Technology Act 2000 and rules made there under, the name and contact details of the Grievance Officer are provided below:</p>
            <p>Mr Madhusudan</p>
            <p>+91 9980039586</p>
            <h4> Note: </h4>
            <p>Our privacy policy is subject to change at any time without notice. To make sure you are aware of any changes, please review this policy periodically.</p>
            <p>By visiting this Website you agree to be bound by the terms and conditions of this Privacy Policy. If you do not agree please do not use or access our Website or App.</p>
            <p>By mere use of the Website / app, you expressly consent to our use and disclosure of your personal information in accordance with this Privacy Policy. This Privacy Policy is incorporated into and subject to the Terms of Use. </p>
            </div>
        )
    }
}
export {PrivacyPage}